name: Java CI with Gradle

on:
  push:
    branches:
      - "main"
      - "dev"
      - "BE_dev"
  pull_request:
    type: closed
    branches:
      - "main"
      - "dev"
      - "FE_dev"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: backend
